# Generated by Django 4.0 on 2022-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajo',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='bateria',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='guitarra',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='pedal',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='teclado',
            name='instrumento',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipoInstrumento',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Amplificador',
        ),
        migrations.DeleteModel(
            name='Bajo',
        ),
        migrations.DeleteModel(
            name='Bateria',
        ),
        migrations.DeleteModel(
            name='Guitarra',
        ),
        migrations.DeleteModel(
            name='Pedal',
        ),
        migrations.DeleteModel(
            name='Teclado',
        ),
    ]
