# Generated by Django 4.0 on 2022-05-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_instrumento_instrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='tipoInstrumento',
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='instrumento',
            field=models.CharField(choices=[('guitarra', 'Guitarra'), ('bajo', 'Bajo'), ('pedal', 'Pedal'), ('bateria', 'Bateria'), ('teclado', 'Teclado'), ('amplificador', 'Amplificador'), ('otro', 'Otro')], default='guitarra', max_length=15),
        ),
    ]
