# Generated by Django 4.0 on 2022-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_instrumento_imageninstrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='imagenInstrumento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
