# Generated by Django 4.0 on 2022-05-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_remove_comentario_name_comentario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='body',
            new_name='mensaje',
        ),
    ]
