# Generated by Django 4.0 on 2022-05-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_rename_body_comentario_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Base.instrumento'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
