# Generated by Django 4.0 on 2022-05-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_comentario_options_alter_instrumento_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
